# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWEcYP0CXAwLjtN6JH_Zd3nTnD6w1Xrq
"""



import csv
import datetime

print("Bir pizza tabanı seçiniz.")
print("1)Klasik Pizza (49TL)")
print("2)Margarita (56TL)")
print("3)Türk Pizzası (59TL)")
print("4)Sade Pizza (44TL)")


taban = input("Lütfen bir pizza tabanı seçiniz (1-4): ")


if taban == "1":
    fiyat = 49
    taban_adi = "Klasik Pizza"
elif taban == "2":
    fiyat = 56
    taban_adi = "Margarita"
elif taban == "3":
    fiyat = 59
    taban_adi = "Türk Pizzası"
elif taban == "4":
    fiyat = 44
    taban_adi = "Sade Pizza"
else:
    print("Hatalı seçim yaptınız!")
    exit()


print("Lütfen en az 1, en fazla 6 adet ek malzeme seçiniz.")
print("5)Zeytin (19TL)")
print("6)Mantar (14TL)")
print("7)Keçi Peyniri (22TL)")
print("8)Sucuk (29TL)")
print("9)Soğan (15TL)")
print("10)Mısır (18TL)")


fiyat_toplam = 0
secimler = []
while len(secimler) < 10:
    secim = input("Lütfen bir ek malzeme seçiniz (5-10) veya çıkış yapmak için 'q' tuşuna basınız: ")
    if secim == "q":
        break
    elif secim not in ["5", "6", "7", "8", "9", "10"]:
        print("Hatalı seçim yaptınız!")
        continue
    elif secim in secimler:
        print("Bu malzemeyi zaten seçtiniz!")
        continue
    else:
        secimler.append(secim)
        if secim == "5":
            fiyat_toplam += 19
        elif secim == "6":
            fiyat_toplam += 14
        elif secim == "7":
            fiyat_toplam += 22
        elif secim == "8":
            fiyat_toplam += 29
        elif secim == "9":
            fiyat_toplam += 15
        elif secim == "10":
            fiyat_toplam += 18


toplam_fiyat = fiyat + fiyat_toplam
print("Seçiminiz:", taban_adi, "ve ek malzemeler:", ", ".join(secimler))
print("Top



print("Sipariş vermek için lütfen aşağıdaki bilgileri girin:")


isim = input("Adınız: ")
soyisim = input("Soyadınız: ")


adres = input("Adresiniz: ")


kart_sahibi = input("Kredi kartı sahibinin adı: ")
kart_numarasi = input("Kredi kartı numarası: ")
son_kullanim_tarihi = input("Son kullanım tarihi (mm/yy): ")
güvenlik_kodu = input("Güvenlik kodu: ")


print("Girdiğiniz bilgiler aşağıdaki gibidir:")
print(f"İsim: {isim} {soyisim}")
print(f"Adres: {adres}")
print("Kredi kartı bilgileri:")
print(f"Kart sahibi: {kart_sahibi}")
print(f"Kart numarası: {kart_numarasi}")
print(f"Son kullanım tarihi: {son_kullanim_tarihi}")
print(f"Güvenlik kodu: {güvenlik_kodu}")


with open("Orders_Database.csv", mode="a", encoding="utf-8") as dosya:
   dosya.write(f"{isim},{soyisim},{adres},{kart_sahibi},{kart_numarasi},{son_kullanim_tarihi},{güvenlik_kodu}\n")

print("Siparişiniz başarıyla alınmıştır.")